[package]
name = "tiny_app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libc = "1.0.0-alpha.1"

[profile.release]
opt-level = "s"
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"