[package]
name = "tiny_app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
acap-logging = { version = "0.1.0", default-features = false }

[profile.release]
opt-level = "s"
strip = "symbols"
lto = true
codegen-units = 1
