name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @devcontainers/cli@0.65.0
      - run: devcontainer up --workspace-folder .
      - run: devcontainer exec --workspace-folder . make --always-make check_all
      - run: devcontainer exec --workspace-folder . cargo-acap-build
      - uses: actions/upload-artifact@v4
        with:
          name: 'artifacts'
          path: target/acap/*.eap
